server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: "/dev"
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: "[ACCESS] %{org.apache.catalina.AccessLog.RemoteAddr}r %h %l %u %t trace_id: %{X-B3-TraceId}i %r %s %b"
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

api:
  path: /api/vcreative

env:
  name: dev
  accountType: dev
  accountId: 1

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: never
  endpoints:
    web:
      base-path: ${api.path}

springfox:
  documentation:
    swagger:
      v2:
        path: ${api.path}/docs/latest

spring:
  application:
    name: vcreative-api
  jackson:
    default-property-inclusion: NON_NULL
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    host: 78.128.43.33
    port: 3306
    db: vcreative
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:vcreative}
    password: ${DB_PASSWORD:Vcreative0405!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: false


