server:
  port: 8080

api:
  path: /api/vcreative

env:
  name: dev
  accountType: dev
  accountId: 1

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: never
  endpoints:
    web:
      base-path: ${api.path}

springfox:
  documentation:
    swagger:
      v2:
        path: ${api.path}/docs/latest

spring:
  application:
    name: vcreative-api
  jackson:
    default-property-inclusion: NON_NULL
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    host: localhost
    port: 3307
    db: vcreative
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: vcreative
    password: Vcreative0405!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: false


