version: '2.1'

services:
  postgres:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
