# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11.0.4'
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Login to GitHub Registry Container
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.slaverda }}
          password: ${{ secrets.CR_PAT }}

    - name: Create docker loadbalancer image
      run: docker build -t ghcr.io/myimage/loadbalancer:latest -t ghcr.io/myimage/loadbalancer:$SHA8 ./
      
      
  
